### ISSUE TITLE
adding the content of the django apps to the dashboard

### ISSUE THREAD

**Issue by Shiro1n** [app-generator/django-material-dashboard#10]
hi,
i would like to get help with adding the contents of my apps to the dashboard.
my project structure has apps for the each model for easy management but im having an issue about putting them to the dashboard
this is how my folder structure looks like
![image](https://github.com/app-generator/django-material-dashboard/assets/122375138/8d97fff4-b14b-44bf-9288-5f3d374c895a)

**Comment by app-generator** [comment]
Hello @Shiro1n 

Please pull the latest version `v1.0.11`. 
The templates folder now has `sidebar.html` where you can add new links: 

https://github.com/app-generator/django-material-dashboard/blob/a71bdbe30171cad16b8e1c67d07f961effc346a3/templates/includes/sidebar.html#L80

```html
        <!--
        <li class="nav-item">
          <a class="nav-link text-white {% if 'SEGMENT_HERE' in segment %} active {% endif %} " href="#">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
              <i class="material-icons opacity-10">table_view</i>
            </div>
            <span class="nav-link-text ms-1">LINK_HERE</span>
          </a>
        </li>
        -->
```

Take a look and let us know if helps.
