### ISSUE TITLE
customizing menu_items

### ISSUE THREAD

**Issue by Shiro1n** [app-generator/django-material-dashboard#11]
hi,
i would like to know how we can customize the menu items in sidebar
as i inspected the code is getting app labels and lists the models of the app under the app label with querys thats great but lets say for example i dont want it to include one model or lets say i want to gather models under a diffrent name. i know this might broke the dynamic structure but thats what i need.
i would be appriciated if you help me with that.

**Comment by mominur-helios** [comment]
Hello @Shiro1n ,

It seems your requirements is not clear. Could you please clarify it in more details!

**Comment by Shiro1n** [comment]
Hello @mominur-helios,
i have inspected the code to understand dynamic structure of the sidebar but im not quite familiar with usage of django templates
what i discovered was the app labels are listed in the sidebar, and the models of the apps are listed under the labels of their apps.
so what i would like to achieve is instead of using the labels of the apps couldnt we use a custom name for the models
for example i want to make a model group named purchase and it will contain models from diffrent apps in my project
or i dont want to include one model of my app to the list
what i meant by the models are the admin urls by the way
if you need any more details please contact me
thanks.

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
